name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.platform.name }} Build
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows, os: windows-latest }
        - { name: Linux, os: ubuntu-latest }
        - { name: MacOS, os: macos-latest }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libsfml-dev

    - name: Install MacOS Dependencies
      if: runner.os == 'macOS'
      run: brew install sfml

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      shell: bash
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} ${{matrix.config.flags}}

    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Install
      shell: bash
      run: cmake --install build --config Release
